/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.freedesktop.dbus.connections.impl.DBusConnection;
import org.freedesktop.dbus.connections.impl.DBusConnectionBuilder;
import org.freedesktop.dbus.interfaces.DBusSigHandler;

import java.util.Map;

public class App {
    public DBusConnection receive() throws Exception {
        final var busType = DBusConnection.DBusBusType.SESSION;
        final var dBusConn = DBusConnectionBuilder.forType(busType).build();
        var signal = dBusConn.getRemoteObject("org.example.App", "/test", Signal.class);
        System.out.println("GOT " + signal.getObjectPath());

        final DBusSigHandler<Signal.MessageReceivedV2> dbusMsgHandler = messageReceived -> {
            System.out.println("Received: " + messageReceived.getMessage());
        };
        dBusConn.addSigHandler(Signal.MessageReceivedV2.class, signal, dbusMsgHandler);
        return dBusConn;
    }

    public DBusConnection export() throws Exception {
        final var busType = DBusConnection.DBusBusType.SESSION;
        var dBusConn = DBusConnectionBuilder.forType(busType).build();
        dBusConn.requestBusName("org.example.App");
        dBusConn.exportObject(() -> "/test");
        return dBusConn;
    }

    public static void main(String[] args) throws Exception {
        final var app = new App();
        try (var exportDBusConn = app.export();
             var receiveDBusConn = app.receive()) {

            exportDBusConn.sendMessage(new Signal.MessageReceivedV2("/test",
                    System.currentTimeMillis(),
                    "sender",
                    new byte[]{},
                    "message",
                    Map.of()));
            Thread.sleep(3000);
        }
    }
}
